def print_notify(message: str):
    """
    Print an incident report to the console in a formatted style.

    Parameters
    ----------
    message : str
        The incident report text to display (already generated by summarizer).

    Notes
    -----
    This is a simple notifier that outputs to stdout.
    In a real system, this could be extended to:
      - Write to a log file
      - Send to Slack, email, or PagerDuty
      - Trigger alerting pipelines
    """
    # Surround the message with header/footer markers for readability
    print("\n=== INCIDENT REPORT ===\n" + message + "\n=======================\n")
